version: '2'
services:
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  web:
      depends_on:
        - db
      image: jeiddy/jeidinterview
      ports:
        - "8080:8080"
volumes:
  db_data: