package com.patientping.domain;

/**
 * Created by Jacob Eid on 11/23/2016.
 */
import org.hibernate.annotations.Type;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 *
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the userName for the table in the db.
 *
 * @author Jacob Eid
 */
@Entity
@Table(name = "user")
@EntityListeners(AuditingEntityListener.class)
public class User {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer id;

    // The user's userName
    @Column(unique = true)
    @NotNull
    private String userName;

    @Column(columnDefinition = "TINYINT")
    @Type(type = "org.hibernate.type.NumericBooleanType")
    @NotNull
    private Boolean isAdmin = false;

    @Column
    @NotNull
    private String password;

    @CreatedDate
    private Long createDate;

    @LastModifiedDate
    private Long modifiedDate;



    // ------------------------
    // PUBLIC METHODS
    // ------------------------

    public User() { }

    public User(String userName,String password) {
        this.password = password;
        this.userName=userName;
    }

    public Long getCreateDate() {
        return createDate;
    }

    public Long getModifiedDate() {
        return modifiedDate;
    }

    // Getter and setter methods

    public Integer getId() {
        return id;
    }

    public void setId(Integer value) {
        this.id = value;
    }


    public String getUserName() {
        return userName;
    }

    public void setUserName(String value) {
        this.userName = value;
    }

    public Boolean getAdmin() {
        return isAdmin;
    }

    public void setAdmin(Boolean admin) {
        isAdmin = admin;
    }

    public String getPassWord() {
        return password;
    }

    public void setPassWord(String passWord) {
        this.password = passWord;
    }

}